language: php
dist: bionic

php:
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

notifications:
  slack: kumbiaphp:51JaKQTXASwf52D8b32OyWb9
#    irc: "irc.freenode.org#kumbiaphp"
#    email:
#    - programador.manuel@gmail.com


# env:
#  - DB=mysql
#  - DB=pgsql
#  - DB=sqlite

install:
  - composer install
  #- if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require mockery/mockery ~0.9; fi
  #- if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  #- if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
  # Force PHPUnit 7 $TRAVIS_PHP_VERSION > '7.1' rule
  -

script:
  - phpunit --version
  - phpunit --configuration core/phpunit.xml.dist
#  - phpunit --configuration core/phpunit.xml.dist --coverage-text --colors --coverage-clover=coverage.clover
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover